package models.lesson

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "lesson")
data class Lesson(
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "lessonId")
    var lessonId: String = "",
    @DynamoDBAttribute(attributeName = "subjectId")
    var subjectId: String,
    @DynamoDBAttribute(attributeName = "studentId")
    var studentId: String,
    @DynamoDBAttribute(attributeName = "teacherId")
    var teacherId: String,
    @DynamoDBAttribute(attributeName = "price")
    var price: Int = 0,
    @DynamoDBAttribute(attributeName = "status")
    var status: String,
    @DynamoDBAttribute(attributeName = "rating")
    var rating: Int = 0,
    @DynamoDBAttribute(attributeName = "date")
    var date: String = ""
)