package models

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "lesson")
data class Lesson(
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "lessonId")
    var teacherId: String = "",
    @DynamoDBAttribute(attributeName = "price")
    var price: Int = 0,
    @DynamoDBAttribute(attributeName = "status")
    var status: Status = Status.PENDING,
    @DynamoDBAttribute(attributeName = "lessons")
    var lessons: List<String> = listOf(),
    @DynamoDBAttribute(attributeName = "rating")
    var rating: Int = 0,
)