package models.user

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "user")
open class User(
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "userId")
    var userId: String = "",
    @DynamoDBAttribute(attributeName = "firstName")
    var firstName: String = "",
    @DynamoDBAttribute(attributeName = "lastName")
    var lastName: String = "",
    @DynamoDBAttribute(attributeName = "email")
    var email: String = "",
    @DynamoDBAttribute(attributeName = "rating")
    var rating: Int = 0,
    @DynamoDBAttribute(attributeName = "lessons")
    var lessons: List<String> = listOf(),
    @DynamoDBAttribute(attributeName = "userRemoteId")
    var userRemoteId: String = "",
    @DynamoDBAttribute(attributeName = "role")
    var role: String = ""
)