package models.teacher

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "teacher")
data class TeacherDAO(
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "teacherId")
    var teacherId: String = "",
    @DynamoDBAttribute(attributeName = "firstName")
    var firstName: String = "",
    @DynamoDBAttribute(attributeName = "lastName")
    var lastName: String = "",
    @DynamoDBAttribute(attributeName = "subjects")
    var subjects: List<String> = listOf(),
    @DynamoDBAttribute(attributeName = "lessons")
    var lessons: List<String> = mutableListOf(),
    @DynamoDBAttribute(attributeName = "rating")
    var rating: Int = 0,
    @DynamoDBAttribute(attributeName = "hourlyPrice")
    var hourlyPrice: Int = 0,
)