package models.subject

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "subject")
data class Subject(
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "subjectId")
    var subjectId: String = "",
    @DynamoDBAttribute(attributeName = "name")
    var name: String,
    @DynamoDBAttribute(attributeName = "status")
    var teacherId: String,
)